---
- hosts: localhost, hostsgrp
  tasks:
    - name: Get date from localhost
      set_fact:
        datevar: "{{ ansible_date_time.month + ansible_date_time.day + ansible_date_time.hour + ansible_date_time.minute + ansible_date_time.year }}"
        run_once: true
    - name: Distribute date value to hosts
      command: date {{ datevar }}
      register: command_output
      when: inventory_hostname in groups ['hostsgrp']
    - debug:
        var: command_output.stdout_lines
